name: Unit Tests
env:
  # increment this when downloads substantially change to avoid the internet
  DOWNLOAD_CACHE_VERSION: '5'
  RUN_PROCESS_REPLAY: 1

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  docs:
    name: build-docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: pip install -e .[docs]
      - run: mkdocs build --strict